# Generated by Django 5.2 on 2025-09-08 09:55

import api.models
import api.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='staff', max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('headshot', models.FileField(blank=True, null=True, storage=api.storage.PrivateMediaStorage(), upload_to=api.models._headshot_upload_path)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text='Verifier identifier (e.g., email)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_request', to='api.appuser')),
            ],
            options={
                'db_table': 'access_request',
            },
        ),
    ]
