# Generated by Django 5.2.6 on 2025-09-10 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_facetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'password_reset_code',
            },
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_user_id_c922c4_idx',
            old_name='api_refres_user_id_4a3cb5_idx',
        ),
        migrations.RenameIndex(
            model_name='resettoken',
            new_name='reset_token_user_id_1f091f_idx',
            old_name='api_reset__user_id_1d6aee_idx',
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to='api.appuser'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'expires_at', 'used'], name='password_re_user_id_9d14bb_idx'),
        ),
    ]
