# Generated by Django 5.2.6 on 2025-09-10 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passwordresetcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('login', 'Login'), ('action', 'Action'), ('system', 'System'), ('security', 'Security')], default='action', max_length=16)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['type', 'created_at'], name='audit_log_type_5eaa84_idx'), models.Index(fields=['actor_email', 'created_at'], name='audit_log_actor_e_ee18ad_idx')],
            },
        ),
    ]
