# Generated by Django 5.2.6 on 2025-09-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_webpushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_92ac92_idx',
            old_name='notif_user_read_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_90ee72_idx',
            old_name='notif_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_user_id_328508_idx',
            old_name='notif_pref_user_idx',
        ),
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='webpush_sub_user_id_16816c_idx',
            old_name='webpush_user_active_idx',
        ),
    ]
