# Generated by Django 5.2.6 on 2025-09-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_paymenttransaction'),
        ('api', '0012_rename_notif_user_read_created_idx_notificatio_user_id_92ac92_idx_and_more'),
    ]

    operations = [
    ]
