# Generated by Django 5.2.6 on 2025-09-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20250911_1542'),
        ('api', '0013_paymentmethodconfig'),
    ]

    operations = [
    ]
