# Generated by Django 5.2 on 2025-09-11 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20250911_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedule_entry',
            },
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_txn_order_i_983bbe_idx',
            old_name='pay_order_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_txn_method_4660f8_idx',
            old_name='pay_method_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='payment_txn_status_059ec5_idx',
            old_name='pay_status_created_idx',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'created_at'], name='employee_status_738397_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='employee_name_7aabaa_idx'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.employee'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['employee', 'day'], name='schedule_en_employe_1c709c_idx'),
        ),
    ]
