# Generated by Django 5.2.6 on 2025-09-15 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_item',
                'indexes': [models.Index(fields=['name'], name='inventory_i_name_637656_idx'), models.Index(fields=['category'], name='inventory_i_categor_bf879d_idx'), models.Index(fields=['quantity'], name='inventory_i_quantit_dbe9f1_idx'), models.Index(fields=['min_stock'], name='inventory_i_min_sto_20a877_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('restock', 'Restock'), ('usage', 'Usage'), ('adjust', 'Adjust'), ('set', 'Set'), ('expiry_check', 'Expiry Check')], max_length=32)),
                ('quantity_change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_activity',
                'indexes': [models.Index(fields=['item', 'created_at'], name='inventory_a_item_id_df8650_idx'), models.Index(fields=['action', 'created_at'], name='inventory_a_action_deb53f_idx')],
            },
        ),
    ]
