# Generated by Django 5.2.6 on 2025-09-15 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_inventoryitem_inventoryactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inv_batch',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inv_location',
                'indexes': [models.Index(fields=['code'], name='inv_locatio_code_89feac_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReorderSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_settings', to='api.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_settings', to='api.location')),
            ],
            options={
                'db_table': 'inv_reorder_setting',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('SALE', 'Sale/Consumption'), ('ADJUSTMENT', 'Manual Adjustment'), ('WASTE', 'Waste'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return to Supplier')], max_length=16)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('reference_type', models.CharField(blank=True, max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.location')),
            ],
            options={
                'db_table': 'inv_stock_movement',
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['item', 'expiry_date'], name='inv_batch_item_id_9ef8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['lot_code'], name='inv_batch_lot_cod_eab56c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reordersetting',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='uniq_item_location_reorder'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'location', 'effective_at'], name='inv_stock_m_item_id_f2b848_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch'], name='inv_stock_m_batch_i_162b94_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'effective_at'], name='inv_stock_m_movemen_5cb88c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('qty', 0), _negated=True), name='movement_qty_nonzero'),
        ),
    ]
