# Generated by Django 5.2.6 on 2025-09-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_seed_default_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['recorded_at'], name='inv_stock_m_recorde_1979c3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'recorded_at'], name='inv_stock_m_item_id_fba4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location', 'recorded_at'], name='inv_stock_m_locatio_4a6f3c_idx'),
        ),
    ]
