# Generated by Django 5.2.6 on 2025-09-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_stockmovement_inv_stock_m_recorde_1979c3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryactivity',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inventoryactivity',
            name='action',
            field=models.CharField(choices=[('restock', 'Restock'), ('usage', 'Usage'), ('adjust', 'Adjust'), ('set', 'Set'), ('expiry_check', 'Expiry Check'), ('update', 'Update')], max_length=32),
        ),
    ]
