# Generated by Django 5.2.6 on 2025-09-15 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_inventoryactivity_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('preparation_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_item',
                'indexes': [models.Index(fields=['name'], name='menu_item_name_ecb6ca_idx'), models.Index(fields=['category'], name='menu_item_categor_a72ffc_idx'), models.Index(fields=['available'], name='menu_item_availab_0177f9_idx')],
            },
        ),
    ]
