# Generated by Django 5.2.3 on 2025-10-04 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_loginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='api.appuser')),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['category', 'occurred_at'], name='analytics_e_categor_3c6c53_idx'), models.Index(fields=['action', 'occurred_at'], name='analytics_e_action_efa6b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('attendance', 'Attendance'), ('customers', 'Customers')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('range_start', models.DateTimeField(blank=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_snapshots', to='api.appuser')),
            ],
            options={
                'db_table': 'analytics_snapshot',
                'indexes': [models.Index(fields=['category', 'range_start', 'range_end'], name='analytics_s_categor_f567a1_idx'), models.Index(fields=['created_at'], name='analytics_s_created_ac7cb2_idx')],
                'unique_together': {('category', 'range_start', 'range_end')},
            },
        ),
    ]
