# Generated by Django 5.2.3 on 2025-10-04 17:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_analyticsevent_analyticssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catering_event',
                'indexes': [models.Index(fields=['date'], name='catering_ev_date_db3317_idx'), models.Index(fields=['status', 'date'], name='catering_ev_status_8070e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CateringMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_item_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.cateringevent')),
            ],
            options={
                'db_table': 'catering_menu_item',
                'indexes': [models.Index(fields=['event'], name='catering_me_event_i_f61e51_idx')],
            },
        ),
    ]
