# Generated by Django 5.2.3 on 2025-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cateringevent_cateringmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
