# Generated by Django 5.2.3 on 2025-10-08 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_notificationoutbox_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('service', 'Service'), ('food', 'Food'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=32)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to='api.appuser')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to='api.appuser')),
            ],
            options={
                'db_table': 'customer_feedback',
                'indexes': [models.Index(fields=['resolved', 'created_at'], name='customer_fe_resolve_3e75ba_idx'), models.Index(fields=['rating', 'created_at'], name='customer_fe_rating_141be7_idx'), models.Index(fields=['category', 'created_at'], name='customer_fe_categor_248ee9_idx')],
            },
        ),
    ]
