name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django checks
        working-directory: backend
        env:
          DJANGO_DEBUG: '0'
          DJANGO_SECRET_KEY: test-ci-secret
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
        run: |
          python manage.py check --deploy
          python manage.py makemigrations --check --dry-run
      - name: Migrate
        working-directory: backend
        run: python manage.py migrate --noinput
      - name: Run tests (SQLite)
        working-directory: backend
        env:
          DJANGO_DB_ENGINE: sqlite
          DJANGO_SECRET_KEY: test-ci-secret
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
        run: python manage.py test -v 2

